#!/bin/bash

echo "Compiling within directory: $(pwd)"

if [ $1 = "wincompile" ] || [ $1 = "all" ] ;
then
    if [ $2 = "debug" ] ;
    then
        x86_64-w64-mingw32-gcc -g -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -static gather/$3.c -o "binaries" $4 $5 $6 $7 $8 $9
        chmod +x "binaries/$3.exe"
    else
        x86_64-w64-mingw32-gcc -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -static gather/$2.c -o "binaries/$2" $3 $4 $5 $6 $7 $8
        chmod +x "binaries/$2.exe"
    fi
    echo "Created WINDOWS x86 soldier"
fi

if [ $1 = "unixcompile" ] || [ $1 = "all" ] ;
then
    if [ $2 = "debug" ] ;
    then
        gcc -g -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -static gather/$3.c -o "binaries/$3" $4 $5 $6 $7 $8 $9
        chmod +x "binaries/$3"
    else
        gcc -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -static gather/$2.c -o "binaries/$2" $3 $4 $5 $6 $7 $8
        chmod +x "binaries/$2"
    fi
    echo "Created UNIX x86 soldier"
fi

if [ $1 = "unixarmcompile" ] || [ $1 = "all" ] ;
then
    if [ $2 = "debug" ] ;
    then
        arm-none-eabi-gcc -g -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -static gather/$3.c -o "binaries/$3-arm" $4 $5 $6 $7 $8 $9
        chmod +x "binaries/$3-arm"
    else
        arm-none-eabi-gcc -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -static gather/$2.c -o "binaries/$2-arm" $3 $4 $5 $6 $7 $8
        chmod +x "binaries/$2-arm"
    fi
    echo "Created UNIX ARM soldier"

fi

exit

