#!/bin/sh

	gcc -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast $2 -static $1.c -o $1 $3 # MUST HAVE 'musl-tools' INSTALLED

# Alternate: 
	# gcc -static play.c -o play 
	# OR 
	# gcc play.c -o play # (dynamic executable version)

exit

