#!/bin/sh

arm-linux-gnueabi-gcc $2 -static $1.c -o armplay $3 # MUST HAVE 'arm-linux-gnueabi-gcc' COMPILER INSTALLED

# OR

# arm-linux-gnueabi-gcc play.c -o play # (Dynamic executable version)

exit

